version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:80"
    networks:
      - laravel

  db:
    image: mysql:5.7
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shopsys
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3307"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
